import {
  red,
  pink,
  purple,
  deepPurple,
  indigo,
  blue,
  lightBlue,
  cyan,
  teal,
  green,
  lightGreen,
  lime,
  yellow,
  amber,
  orange,
  deepOrange,
} from "@material-ui/core/colors";

export const appSettings = {
  isDark: true,
  isAmoled: false,
  eventView: "",
  eventEditMode: false,
  filters: [],
};

export const eventList = [
  /* {
      id: "2",
      title: "Piggy bday",
      startDate: "1992-09-05T18:30:00.000Z",
      createdDate: "2013-02-02T18:30:00.000Z",
      description: "The birthday of Piggy.",
      checkedDays: false,
      checkedMonths: true,
      checkedYears: false,
      completedEvent: false,
      setReminder: true,
      lastEditedDate: "2020-06-23T06:54:04.177Z",
      edit: false,
      favourite: true,
      archived: false,
      tags: ["Birthdays"],
      duration: "28 years ago",
      endDate: "",
      finishedDuration: "",
    }, */
  {
    id: "1",
    title: "B day",
    startDate: "1990-08-05T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "My birthday.",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: true,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2020-06-23T06:50:02.079Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: ["Birthdays", "Personal"],
    duration: "30 years ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "3",
    title: "Joined Neudesic",
    startDate: "2020-01-05T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Joined Neudesic Kochi.",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: false,
    lastEditedDate: "2020-06-23T06:50:41.136Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: ["Work", "Neudesic"],
    duration: "6 months ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "4",
    title: "Joined CTS",
    startDate: "2013-02-02T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "The day that I joined Cognizant.",
    checkedDays: true,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: true,
    setReminder: false,
    endDate: "2019-12-23T17:24:56.100Z",
    lastEditedDate: "2020-06-23T06:50:48.974Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: ["Work", "CTS"],
    duration: "7 years ago",
    finishedDuration: "7 years 11 months and 24 days!",
  },
  {
    id: "5",
    title: "Next month 1",
    startDate: "2020-09-24T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2020-06-23T06:51:34.396Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: [],
    duration: "90 years ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "6",
    title: "Max characters we can type= 30",
    startDate: "1950-03-24T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something else happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: true,
    completedEvent: false,
    setReminder: false,
    lastEditedDate: "2020-06-23T06:51:22.223Z",
    edit: false,
    favourite: true,
    archived: false,
    tags: [
      "Birthdays",
      "Insurance",
      "Work",
      "Vehicle",
      "Neudesic",
      "CTS",
      "Health",
      "Fitness",
      "Finance",
      "Devices",
      "MutualFunds",
      "Important",
      "Personal",
      "Learning",
      "To Do",
    ],
    duration: "70 years ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "7",
    title: "Next month 2",
    startDate: "2020-09-01T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Then something more happened",
    checkedDays: true,
    checkedMonths: true,
    checkedYears: true,
    completedEvent: false,
    setReminder: false,
    lastEditedDate: "2020-06-23T06:51:14.078Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: [],
    duration: "50 years ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "8",
    title: "|--- Lockdown ---|",
    startDate: "2020-03-24T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "The COVID-19 nation-wide lockdown.",
    checkedDays: false,
    checkedMonths: true,
    checkedYears: false,
    completedEvent: false,
    setReminder: false,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: [],
    duration: "3 months ago",
    endDate: "",
    finishedDuration: "",
  },
  {
    id: "9",
    title: "Something archived",
    startDate: "1930-03-25T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: true,
    tags: [],
  },
  {
    id: "10",
    title: "Something archived again",
    startDate: "1930-03-25T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: true,
    tags: [],
  },
  {
    id: "11",
    title: "Something else archived next month",
    startDate: "2020-09-01T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: true,
    tags: [],
  },
  {
    id: "12",
    title: "Same month",
    startDate: "2020-08-28T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: [],
  },
  {
    id: "13",
    title: "Same month before",
    startDate: "2020-08-01T18:30:00.000Z",
    createdDate: "2013-02-02T18:30:00.000Z",
    description: "Something happened",
    checkedDays: false,
    checkedMonths: false,
    checkedYears: false,
    completedEvent: false,
    setReminder: true,
    lastEditedDate: "2013-02-02T18:30:00.000Z",
    edit: false,
    favourite: false,
    archived: false,
    tags: [],
  },
];

export const eventTags = [
  { tagName: "Birthdays", colour: red["A700"] },
  { tagName: "Work", colour: pink["A700"] },
  { tagName: "Vehicle", colour: purple["A700"] },
  { tagName: "Insurance", colour: deepPurple["A700"] },
  { tagName: "Neudesic", colour: indigo["A700"] },
  { tagName: "CTS", colour: blue["A700"] },
  { tagName: "Health", colour: lightBlue["A700"] },
  { tagName: "Fitness", colour: cyan["A700"] },
  { tagName: "MutualFunds", colour: teal["A700"] },
  { tagName: "Finance", colour: green["A700"] },
  { tagName: "Devices", colour: lightGreen["A700"] },
  { tagName: "Important", colour: lime["A700"] },
  { tagName: "Personal", colour: yellow["A700"] },
  { tagName: "To Do", colour: amber["A700"] },
  { tagName: "Learning", colour: orange["A700"] },
  { tagName: "Investments", colour: deepOrange["A700"] },
];
